package model

const CurrentVersion = 1

type Config struct {
	Version  int
	Settings Settings
	Domains  []Domain
	Services []Service
	Exits    []Exit
	Bindings []Binding
}

type Settings struct {
	StateDir       string
	SecretsPath    string
	Nginx          NginxSettings
	ACME           ACMESettings
	FRP            FRPSettings
	Cloudflare     CloudflareSettings
	GeneratedByTag string
}

type NginxSettings struct {
	GeneratedDir  string
	TestCommand   string
	ReloadCommand string
}

type ACMESettings struct {
	Enabled     bool
	Provider    string
	Email       string
	CertDir     string
	ACMEShPath  string
	ACMEShECC   bool
	ACMEShDNS   string
	ACMEShServer string
}

type FRPSettings struct {
	Enabled       bool
	InstallDir    string
	ConfigDir     string
	SystemdDir    string
	ServicePrefix string
	ManageSystemd bool
	ReloadCommand string
}

type CloudflareSettings struct {
	Enabled        bool
	ConflictPolicy string
}

type Domain struct {
	Name            string
	Provider        string
	ZoneRef         string
	ZoneID          string
	TokenRef        string
	DefaultProxied  bool
	AllowDNSUpdates bool
	AllowACME       bool
}

type Service struct {
	Name     string
	Protocol string
	Host     string
	Port     int
	Options  ServiceOptions
}

type ServiceOptions struct {
	Websocket         bool
	BackendTLSVerify  string
	ConnectTimeout    string
	SendTimeout       string
	ReadTimeout       string
	ClientMaxBodySize string
	Buffering         string
	RequestBuffering  string
	RangeMode         string
}

type Exit struct {
	Name       string
	Type       string
	Domain     string
	DNSTargets []DNSTarget
	FRP        FRPExit
}

type DNSTarget struct {
	Type  string
	Value string
}

type FRPExit struct {
	ServerAddr      string
	ServerPort      int
	TokenRef        string
	TLS             bool
	RemoteHTTPSPort int
	LocalHTTPSPort  int
}

type Binding struct {
	Name         string
	Service      string
	Exit         string
	Hostname     string
	SSL          bool
	Proxied      bool
	ExternalPort int
	CertName     string
	Disabled     bool
}

type Secrets struct {
	CloudflareZones  map[string]string
	CloudflareTokens map[string]string
	FRPTokens        map[string]string
}

func (c *Config) ApplyDefaults() {
	if c.Version == 0 {
		c.Version = CurrentVersion
	}
	if c.Settings.StateDir == "" {
		c.Settings.StateDir = "/var/lib/lantern"
	}
	if c.Settings.SecretsPath == "" {
		c.Settings.SecretsPath = "secrets.yaml"
	}
	if c.Settings.Nginx.GeneratedDir == "" {
		c.Settings.Nginx.GeneratedDir = "/etc/nginx/conf.d/lantern"
	}
	if c.Settings.Nginx.TestCommand == "" {
		c.Settings.Nginx.TestCommand = "nginx -t"
	}
	if c.Settings.Nginx.ReloadCommand == "" {
		c.Settings.Nginx.ReloadCommand = "systemctl reload nginx"
	}
	if c.Settings.ACME.Provider == "" {
		c.Settings.ACME.Provider = "lego"
	}
	if c.Settings.ACME.CertDir == "" {
		if c.Settings.ACME.Provider == "acme.sh" {
			c.Settings.ACME.CertDir = "/root/.acme.sh"
		} else {
			c.Settings.ACME.CertDir = "/etc/lantern/certs"
		}
	}
	if c.Settings.ACME.ACMEShPath == "" {
		c.Settings.ACME.ACMEShPath = "/root/.acme.sh/acme.sh"
	}
	if c.Settings.ACME.ACMEShDNS == "" {
		c.Settings.ACME.ACMEShDNS = "dns_cf"
	}
	if c.Settings.FRP.InstallDir == "" {
		c.Settings.FRP.InstallDir = "/opt/frp"
	}
	if c.Settings.FRP.ConfigDir == "" {
		c.Settings.FRP.ConfigDir = "/etc/frp"
	}
	if c.Settings.FRP.SystemdDir == "" {
		c.Settings.FRP.SystemdDir = "/etc/systemd/system"
	}
	if c.Settings.FRP.ServicePrefix == "" {
		c.Settings.FRP.ServicePrefix = "lantern-frpc"
	}
	if c.Settings.Cloudflare.ConflictPolicy == "" {
		c.Settings.Cloudflare.ConflictPolicy = "prompt"
	}
	if c.Settings.GeneratedByTag == "" {
		c.Settings.GeneratedByTag = "generated by Lantern; edit lantern.yaml instead"
	}
	for i := range c.Services {
		if c.Services[i].Options.BackendTLSVerify == "" {
			c.Services[i].Options.BackendTLSVerify = "on"
		}
		if c.Services[i].Options.ConnectTimeout == "" {
			c.Services[i].Options.ConnectTimeout = "30s"
		}
		if c.Services[i].Options.SendTimeout == "" {
			c.Services[i].Options.SendTimeout = "300s"
		}
		if c.Services[i].Options.ReadTimeout == "" {
			c.Services[i].Options.ReadTimeout = "300s"
		}
		if c.Services[i].Options.ClientMaxBodySize == "" {
			c.Services[i].Options.ClientMaxBodySize = "0"
		}
		if c.Services[i].Options.Buffering == "" {
			c.Services[i].Options.Buffering = "default"
		}
		if c.Services[i].Options.RequestBuffering == "" {
			c.Services[i].Options.RequestBuffering = "default"
		}
		if c.Services[i].Options.RangeMode == "" {
			c.Services[i].Options.RangeMode = "default"
		}
	}
	for i := range c.Exits {
		if c.Exits[i].FRP.ServerPort == 0 {
			c.Exits[i].FRP.ServerPort = 7000
		}
		if c.Exits[i].FRP.RemoteHTTPSPort == 0 {
			c.Exits[i].FRP.RemoteHTTPSPort = 8443
		}
		if c.Exits[i].FRP.LocalHTTPSPort == 0 {
			c.Exits[i].FRP.LocalHTTPSPort = 443
		}
	}
}

func ExampleConfig() *Config {
	cfg := &Config{
		Version: CurrentVersion,
		Settings: Settings{
			StateDir:    ".lantern/state",
			SecretsPath: "secrets.yaml",
			Nginx: NginxSettings{
				GeneratedDir:  ".lantern/nginx",
				TestCommand:   "nginx -t",
				ReloadCommand: "systemctl reload nginx",
			},
			ACME: ACMESettings{
				Enabled:  false,
				Provider: "lego",
				Email:    "admin@example.com",
				CertDir:  ".lantern/certs",
				ACMEShPath: "/root/.acme.sh/acme.sh",
				ACMEShDNS:  "dns_cf",
			},
			FRP: FRPSettings{
				Enabled:       true,
				InstallDir:    "/opt/frp",
				ConfigDir:     ".lantern/frp",
				SystemdDir:    ".lantern/systemd",
				ServicePrefix: "lantern-frpc",
				ManageSystemd: false,
			},
			Cloudflare: CloudflareSettings{
				Enabled:        true,
				ConflictPolicy: "prompt",
			},
		},
		Domains: []Domain{
			{
				Name:            "lan.site-2.teclab.org.cn",
				Provider:        "cloudflare",
				ZoneRef:         "cf_teclab_zone",
				TokenRef:        "cf_teclab",
				DefaultProxied:  false,
				AllowDNSUpdates: true,
				AllowACME:       true,
			},
			{
				Name:            "site-2.teclab.org.cn",
				Provider:        "cloudflare",
				ZoneRef:         "cf_teclab_zone",
				TokenRef:        "cf_teclab",
				DefaultProxied:  true,
				AllowDNSUpdates: true,
				AllowACME:       true,
			},
		},
		Services: []Service{
			{
				Name:     "bitshare",
				Protocol: "http",
				Host:     "192.168.1.244",
				Port:     13830,
				Options: ServiceOptions{
					Buffering:        "off",
					RequestBuffering: "off",
					ReadTimeout:      "600s",
					SendTimeout:      "600s",
					RangeMode:        "pass",
				},
			},
		},
		Exits: []Exit{
			{
				Name:   "lan",
				Type:   "direct",
				Domain: "lan.site-2.teclab.org.cn",
				DNSTargets: []DNSTarget{
					{Type: "A", Value: "auto:public-ipv4"},
					{Type: "AAAA", Value: "auto:public-ipv6"},
				},
			},
			{
				Name:   "site1-frp",
				Type:   "frp",
				Domain: "site-2.teclab.org.cn",
				DNSTargets: []DNSTarget{
					{Type: "AAAA", Value: "2001:db8::1"},
				},
				FRP: FRPExit{
					ServerAddr:      "site-1.teclab.org.cn",
					ServerPort:      7000,
					TokenRef:        "frp_site1",
					TLS:             true,
					RemoteHTTPSPort: 8443,
					LocalHTTPSPort:  443,
				},
			},
		},
		Bindings: []Binding{
			{
				Name:     "bitshare-lan",
				Service:  "bitshare",
				Exit:     "lan",
				Hostname: "bitshare.lan.site-2.teclab.org.cn",
				SSL:      true,
				Proxied:  false,
			},
			{
				Name:     "bitshare-public",
				Service:  "bitshare",
				Exit:     "site1-frp",
				Hostname: "bitshare.site-2.teclab.org.cn",
				SSL:      true,
				Proxied:  true,
			},
		},
	}
	cfg.ApplyDefaults()
	return cfg
}

func ExampleSecrets() *Secrets {
	return &Secrets{
		CloudflareZones: map[string]string{
			"cf_teclab_zone": "replace-with-cloudflare-zone-id",
		},
		CloudflareTokens: map[string]string{
			"cf_teclab": "replace-with-cloudflare-api-token",
		},
		FRPTokens: map[string]string{
			"frp_site1": "replace-with-frp-token",
		},
	}
}
